config/routes.rb
Rails.application.routes.draw do
  devise_for :dogs
  root to: "dogs#index"
  resources :barks
  resources :dogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bark.rb
class Bark < ApplicationRecord
  belongs_to :dog
end

app/models/dog.rb
class Dog < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :barks

  def number_of_barks
    self.barks.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/barks_controller.rb
class BarksController < ApplicationController
  before_action :set_bark, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_dog!, only: [:new, :edit, :create, :update, :destroy]

  # GET /barks
  # GET /barks.json
  def index
    @barks = Bark.all
  end

  # GET /barks/1
  # GET /barks/1.json
  def show
  end

  # GET /barks/new
  def new
    @bark = Bark.new
  end

  # GET /barks/1/edit
  def edit
  end

  # POST /barks
  # POST /barks.json
  def create
    @bark = Bark.new(bark_params)

    respond_to do |format|
      if @bark.save
        format.html { redirect_to @bark, notice: 'Bark was successfully created.' }
        format.json { render :show, status: :created, location: @bark }
      else
        format.html { render :new }
        format.json { render json: @bark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barks/1
  # PATCH/PUT /barks/1.json
  def update
    respond_to do |format|
      if @bark.update(bark_params)
        format.html { redirect_to @bark, notice: 'Bark was successfully updated.' }
        format.json { render :show, status: :ok, location: @bark }
      else
        format.html { render :edit }
        format.json { render json: @bark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barks/1
  # DELETE /barks/1.json
  def destroy
    @bark.destroy
    respond_to do |format|
      format.html { redirect_to barks_url, notice: 'Bark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bark
      @bark = Bark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bark_params
      params.require(:bark).permit(:bark, :dog_id)
    end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.all
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)

    respond_to do |format|
      if @dog.save
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :number_of_barks)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barks_helper.rb
module BarksHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/barks/_form.html.erb
<%= form_for(bark) do |f| %>
  <% if bark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bark.errors.count, "error") %> prohibited this bark from being saved:</h2>

      <ul>
      <% bark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bark %>
    <%= f.text_field :bark %>
  </div>

  <div class="field">
    <%= f.label :dog_id %>
    <%= f.number_field :dog_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/barks/edit.html.erb
<h1>Editing Bark</h1>

<%= render 'form', bark: @bark %>

<%= link_to 'Show', @bark %> |
<%= link_to 'Back', barks_path %>

app/views/barks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Barks</h1>

<table>
  <thead>
    <tr>
      <th>Bark</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barks.each do |bark| %>
      <tr>
        <td><%= bark.bark %></td>
        <td><%= bark.dog_id %></td>
        <td><%= link_to 'Show', bark %></td>
        <td><%= link_to 'Edit', edit_bark_path(bark) %></td>
        <td><%= link_to 'Destroy', bark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bark', new_bark_path %>

app/views/barks/new.html.erb
<h1>New Bark</h1>

<%= render 'form', bark: @bark %>

<%= link_to 'Back', barks_path %>

app/views/barks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bark:</strong>
  <%= @bark.bark %>
</p>

<p>
  <strong>Author:</strong>
  <%= @bark.dog_id %>
</p>

<%= link_to 'Edit', edit_bark_path(@bark) %> |
<%= link_to 'Back', barks_path %>

app/views/dogs/_form.html.erb
<%= form_for(dog) do |f| %>
  <% if dog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dog.errors.count, "error") %> prohibited this dog from being saved:</h2>

      <ul>
      <% dog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dogs/edit.html.erb
<h1>Editing Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Show', @dog %> |
<%= link_to 'Back', dogs_path %>

app/views/dogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of barks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dogs.each do |dog| %>
      <tr>
        <td><%= dog.name %></td>
        <td><%= dog.number_of_barks %></td>
        <td><%= link_to 'Show', dog %></td>
        <td><%= link_to 'Edit', edit_dog_path(dog) %></td>
        <td><%= link_to 'Destroy', dog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dog', new_dog_path %>

app/views/dogs/new.html.erb
<h1>New Dog</h1>

<%= render 'form', dog: @dog %>

<%= link_to 'Back', dogs_path %>

app/views/dogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dog.name %>
</p>

<p>
  <strong>Number of barks:</strong>
  <%= @dog.number_of_barks %>
</p>

<%= link_to 'Edit', edit_dog_path(@dog) %> |
<%= link_to 'Back', dogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogTwitter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>